(add-to-list 'custom-theme-load-path
             (file-name-as-directory "~/.emacs.d/lisp/"))
(load-theme 'tty-dark t)

(custom-set-faces
; '(default ((t (:background "default" :foreground "default"))))
 '(vertical-border ((t (:background "#4e4e4e" :foreground "#4e4e4e"))))
 '(dircolors-face-dir ((t (:foreground "brightblue"))))
 '(highlight ((t (:background "#0000ff" :foreground "yellow"))))
 '(isearch-fail ((t (:background "#d7afaf" :foreground "black"))))
 '(lazy-highlight ((t (:background "paleturquoise" :foreground "black"))))
 '(match ((t (:foreground "#00ffff"))))
 '(minibuffer-prompt ((t (:foreground "brightcyan"))))
 '(mode-line ((t (:background "#4e4e4e" :foreground "#ffae00"))))
 '(mode-line-buffer-id ((t (:background "#303030" :foreground "red"))))
 '(mode-line-inactive ((t (:inherit 'mode-line :background "#303030" :foreground "#121212"))))
 '(region ((t (:inverse-video t :foreground nil :background nil))))
 '(show-paren-match ((t (:inverse-video t :foreground nil :background nil))))
 '(whitespace-trailing ((t (:background "DarkRed"))))
 '(whitespace-space ((t (:background "LightSlateGray"))))
 '(whitespace-tab ((t (:foreground "LightSlateGray" :underline t))))
 '(whitespace-line ((t (:background "#5f0000" :foreground nil))))
 '(flyspell-incorrect ((t (:underline t))))
 '(flyspell-duplicate ((t (:underline t))))
 '(flycheck-warning ((t (:inherit nil))))
 '(flycheck-error ((t (:underline t :foreground "orange"))))
 '(font-lock-variable-name-face ((t (:foreground "brightblue"))))
 '(font-lock-builtin-face ((t (:foreground "brightblue"))))
 '(flycheck-warning ((t (:inherit nil))))
 '(company-preview ((t (:foreground "darkgray" :underline t))))
 '(company-preview-common ((t (:inherit company-preview))))
 '(company-tooltip ((t (:background "lightgray" :foreground "black"))))
 '(company-tooltip-common ((((type x)) (:inherit company-tooltip :weight bold)) (t (:inherit company-tooltip))))
 '(company-tooltip-common-selection ((((type x)) (:inherit company-tooltip-selection :weight bold)) (t (:inherit company-tooltip-selection))))
 '(company-tooltip-selection ((t (:background "steelblue" :foreground "white"))))
 '(lsp-ui-sideline-global ((t (:background "#6c6c6c"))))
 '(lsp-ui-sideline-symbol ((t (:foreground "brightblack" :box (:line-width -1 :color "grey") :height 0.99))))
 '(lsp-ui-sideline-symbol-info ((t (:slant italic :height 0.99))))
 )
