(add-to-list 'custom-theme-load-path
             (file-name-as-directory "~/.emacs.d/lisp/"))
(load-theme 'tty-dark t)

(custom-set-faces
; '(default ((t (:background "default" :foreground "default"))))
 '(vertical-border ((t (:background "#4e4e4e" :foreground "#4e4e4e"))))
 '(dircolors-face-dir ((t (:foreground "brightblue"))))
 '(highlight ((t (:background "#0000ff" :foreground "yellow"))))
 '(isearch-fail ((t (:background "#d7afaf" :foreground "black"))))
 '(lazy-highlight ((t (:background "paleturquoise" :foreground "black"))))
 '(match ((t (:foreground "#00ffff"))))
 '(minibuffer-prompt ((t (:foreground "brightcyan"))))
 '(mode-line ((t (:background "#4e4e4e" :foreground "#ffae00"))))
 '(mode-line-buffer-id ((t (:background "#303030" :foreground "red"))))
 '(mode-line-inactive ((t (:inherit 'mode-line :background "#303030" :foreground "#121212"))))
 '(region ((t (:inverse-video t :foreground nil :background nil))))
 '(show-paren-match ((t (:inverse-video t :foreground nil :background nil))))
 '(dircolors-face-dir ((t (:foreground "brightblue"))))
 '(font-lock-builtin-face ((t (:foreground "brightblue"))))
 '(font-lock-variable-name-face ((t (:foreground "brightblue"))))
 '(highlight ((t (:background "#0000ff" :foreground "yellow"))))
 '(isearch-fail ((t (:background "#d7afaf" :foreground "black"))))
 '(lazy-highlight ((t (:background "paleturquoise" :foreground "black"))))
 '(match ((t (:foreground "#00ffff"))))
 '(minibuffer-prompt ((t (:foreground "brightcyan"))))
 '(mode-line ((t (:background "#4e4e4e" :foreground "#ffae00"))))
 '(mode-line-buffer-id ((t (:background "#303030" :foreground "red"))))
 '(mode-line-inactive ((t (:inherit 'mode-line :background "#303030" :foreground "#121212"))))
 '(region ((t (:inverse-video t :foreground nil :background nil))))
 '(show-paren-match ((t (:inverse-video t :foreground nil :background nil))))
 '(vertical-border ((t (:background "#4e4e4e" :foreground "#4e4e4e"))))
 )

(custom-set-variables
 '(custom-safe-themes
   '("ab91ad83f4c9e12a8d01458e83954fd244541eb9412c87d1ab831629c47ad504" default)))
