(require 'auto-complete-config)
(ac-config-default)
(ac-flyspell-workaround)
(setq ac-use-menu-map t)
(setq ac-use-fuzzy nil)
(setq ac-disable-inline t)
(setq ac-candidate-menu-min 0)
(setq ac-comphist-file "~/.ac-comphist")

(define-key ac-complete-mode-map "\C-n" 'ac-next)
(define-key ac-complete-mode-map "\C-p" 'ac-previous)
