(require 'lsp-mode)
(add-hook 'go-mode-hook
          (lambda ()
            (setq tab-width 2)
            (add-hook 'before-save-hook 'gofmt-before-save)
            (set (make-local-variable 'whitespace-style) '(face trailing lines-tail empty space))
            (local-set-key (kbd "C-c C-f") 'gofmt)
            (local-set-key (kbd "C-c C-a") '(lambda () (interactive) (go-import-add t (replace-regexp-in-string "^[\"']\\|[\"']$" "" (completing-read "Package: " (go--old-completion-list-style (go-packages)))))))
            (local-set-key (kbd "C-c C-o") 'xref-find-definitions-other-window)
            (local-set-key (kbd "C-c C-j") 'xref-find-definitions)
            (local-set-key (kbd "C-c C-i") 'lsp-ui-peek-find-implementation)
            (local-set-key (kbd "C-c C-n") 'lsp-rename)
            (local-set-key (kbd "C-c C-r") 'go-remove-unused-imports)
            (local-set-key (kbd "C-c C-e") 'flycheck-next-error)
))

(add-hook 'go-mode-hook #'lsp)
