;; Built-in tree-sitter modes - no package installation needed
(add-to-list 'auto-mode-alist '("\\.ts\\'" . typescript-ts-mode))
(add-to-list 'auto-mode-alist '("\\.tsx\\'" . tsx-ts-mode))

(when (require 'lsp-mode nil t)
  (add-hook 'js-mode-hook
          (lambda ()
            (make-local-variable 'js-indent-level)
            (setq js-indent-level 2)
            (lsp)
            (local-set-key (kbd "C-c C-t") 'xref-find-type-definitions-other-window)
            (local-set-key (kbd "C-c C-o") 'xref-find-definitions-other-window)
            (local-set-key (kbd "C-c C-j") 'xref-find-definitions)
            (when (require 'lsp-ui nil t)
              (local-set-key (kbd "C-c C-i") 'lsp-ui-peek-find-implementation))
            (local-set-key (kbd "C-c C-n") 'lsp-rename)
            (when (fboundp 'flycheck-previous-error)
              (local-set-key (kbd "C-c e") 'flycheck-previous-error)
              (local-set-key (kbd "C-c C-e") 'flycheck-next-error))
            (local-set-key (kbd "C-c C-d") 'lsp-describe-thing-at-point-minibuffer)
          ))
  
  (add-hook 'typescript-ts-mode-hook
          (lambda ()
            (lsp)
            (local-set-key (kbd "C-c C-t") 'xref-find-type-definitions-other-window)
            (local-set-key (kbd "C-c C-o") 'xref-find-definitions-other-window)
            (local-set-key (kbd "C-c C-j") 'xref-find-definitions)
            (when (require 'lsp-ui nil t)
              (local-set-key (kbd "C-c C-i") 'lsp-ui-peek-find-implementation))
            (local-set-key (kbd "C-c C-n") 'lsp-rename)
            (when (fboundp 'flycheck-previous-error)
              (local-set-key (kbd "C-c e") 'flycheck-previous-error)
              (local-set-key (kbd "C-c C-e") 'flycheck-next-error))
            (local-set-key (kbd "C-c C-d") 'lsp-describe-thing-at-point-minibuffer)
          ))
  
  (add-hook 'tsx-ts-mode-hook
          (lambda ()
            (lsp)
            (local-set-key (kbd "C-c C-t") 'xref-find-type-definitions-other-window)
            (local-set-key (kbd "C-c C-o") 'xref-find-definitions-other-window)
            (local-set-key (kbd "C-c C-j") 'xref-find-definitions)
            (when (require 'lsp-ui nil t)
              (local-set-key (kbd "C-c C-i") 'lsp-ui-peek-find-implementation))
            (local-set-key (kbd "C-c C-n") 'lsp-rename)
            (when (fboundp 'flycheck-previous-error)
              (local-set-key (kbd "C-c e") 'flycheck-previous-error)
              (local-set-key (kbd "C-c C-e") 'flycheck-next-error))
            (local-set-key (kbd "C-c C-d") 'lsp-describe-thing-at-point-minibuffer)
          )))
